<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$contenedores = [
"titulo" => "CON TENEDOR",
"autor" => "SIN TENEDOR",
"resumen" => "HOLA COMO ESTAS ESTA NOCHE QUIERO HACER MALDADES ESTA QUIERO HACERTELO Y QUE NO ACABE HACER QUE TE ENTREGUES A MI",
];
?>
