<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$cultura = [
"titulo" => "PERU POTENCIAL MUNDIAL CON MACHU PICCHU",
"autor" => "ARQUEOLOGOS",
"resumen" => "MARAVILLA DEL MUNDO",
];
?>
