<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$formacion = [
"titulo" => "POLICIA",
"autor" => "sistemas@uns",
"resumen" => "DEL PERU ARRESTAN A DELICNUETNES QUE IBAN VESTIDOS DE PAYASOS POR FIESTA DE HALLOWEEN , BALACENA A DUEÑO DE LOCAL",
];
?>
