<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$gente = [
"titulo" => "VALENCIA AFECTADOS POR INUNDACIONES",
"autor" => "ESPAÑOLES ASUSTADOS",
"resumen" => "ACCIDENTE DE TRANSITO AEREO TERRESTE Y MAS",
];
?>
