<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$git = [
"titulo" => "{QUE ES UN GIT?",
"autor" => "GIT",
"resumen" => "SOLO ES GIT HUB O GIT DE LA BANDA MUSICAL ARGENTINA QUE TUVO UN IMPACTO ENE LA INDUTSTRI MUSICAL ESPAÑOL Y PERUANA",
];
?>
