<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$internacional = [
"titulo" => "GANAMOS LA EUROCOPA CON JOSE GALVEZ",
"autor" => "CHIMBOTANOS",
"resumen" => "PERUANOS EN EL EXTRANJERO",
];
?>
