<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$nacional = [
"titulo" => "DINA BOLUARTE SE RELANZA PARA PRESIDENTA",
"autor" => "TVPERU",
"resumen" => "CASTILLO AL PODER",
];
?>
