<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$openshift = [
"titulo" => "VALERIO ARREGLO EL BUG DE GLOUD APP DEPLOY",
"autor" => "JHON CENA",
"resumen" => "UNA REINICIADA FUE SUFICIENTE",
];
?>
